/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.contacteditor;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import my.contacteditor.conexao.conexaoBD;

/**
 *
 * @author  Lucas Tassi
 *          Lucas Diniz
 *          Lucas Barbosa
 *          Jhordan Garcia
 */
public class alterarExcluirForn extends javax.swing.JFrame {
    
    /**
     * Creates new form alterarExcluirForn
     */
    public alterarExcluirForn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tel2Forn = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bairroForn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numeroForn = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        cnpj = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        nomeForn = new javax.swing.JTextField();
        ruaForn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cepForn = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tel1Forn = new javax.swing.JFormattedTextField();
        consultarForn = new javax.swing.JButton();
        limparCampos = new javax.swing.JButton();
        cancelarBotao = new javax.swing.JButton();
        excluirForn = new javax.swing.JButton();
        alterarForn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        razaoSocForn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        inscEst = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        estadoForn = new javax.swing.JTextField();
        cidadeForn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel6.setText("*Rua");

        try {
            tel2Forn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("*Número");

        jLabel8.setText("Bairro");

        jLabel9.setText("CEP");

        numeroForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFornActionPerformed(evt);
            }
        });

        jLabel10.setText("Telefone 2");

        try {
            cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjActionPerformed(evt);
            }
        });

        jLabel1.setText("*Nome Fantasia:  ");

        nomeForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFornActionPerformed(evt);
            }
        });

        ruaForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaFornActionPerformed(evt);
            }
        });

        jLabel3.setText("*Telefone 1");

        jLabel4.setText("*CNPJ:");

        try {
            cepForn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tel1Forn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tel1Forn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel1FornActionPerformed(evt);
            }
        });

        consultarForn.setText("Consultar");
        consultarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarFornActionPerformed(evt);
            }
        });

        limparCampos.setText("Limpar");
        limparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCamposActionPerformed(evt);
            }
        });

        cancelarBotao.setText("Cancelar");
        cancelarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotaoActionPerformed(evt);
            }
        });

        excluirForn.setText("Excluir");
        excluirForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFornActionPerformed(evt);
            }
        });

        alterarForn.setText("Alterar ");
        alterarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFornActionPerformed(evt);
            }
        });

        jLabel2.setText("CONSULTA DE FORNECEDOR");

        jLabel5.setText("*Razão Social:");

        razaoSocForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaoSocFornActionPerformed(evt);
            }
        });

        jLabel11.setText("*Insc. Est.:");

        jLabel12.setText("*Cidade");

        jLabel13.setText("*Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                        .addComponent(alterarForn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirForn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarBotao)
                        .addGap(16, 16, 16))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ruaForn)
                                    .addComponent(bairroForn, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(cidadeForn))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numeroForn)
                                    .addComponent(cepForn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estadoForn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tel1Forn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tel2Forn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(consultarForn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparCampos))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nomeForn, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                        .addComponent(razaoSocForn)
                        .addComponent(inscEst, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(consultarForn)
                    .addComponent(limparCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(razaoSocForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inscEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(numeroForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cepForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bairroForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(estadoForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cidadeForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(tel1Forn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel2Forn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBotao)
                    .addComponent(excluirForn)
                    .addComponent(alterarForn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFornActionPerformed
     
    }//GEN-LAST:event_numeroFornActionPerformed

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed
       
    }//GEN-LAST:event_cnpjActionPerformed

    private void nomeFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFornActionPerformed
        
    }//GEN-LAST:event_nomeFornActionPerformed

    private void ruaFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaFornActionPerformed
       
    }//GEN-LAST:event_ruaFornActionPerformed

    private void tel1FornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel1FornActionPerformed

    }//GEN-LAST:event_tel1FornActionPerformed

    private void consultarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarFornActionPerformed
        conexaoBD cb = new conexaoBD();
        FornecedorDAO forn = null;
        
        
         if(!cnpj.getText().equals(cnpj.getValue())){
            JOptionPane.showMessageDialog(null,"Campo não pode ser vazio!","Erro",JOptionPane.ERROR_MESSAGE,null);
        }else{

            try{
                forn = cb.consultarFornecedor(cnpj.getText());
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"CPNJ não cadastrado","Erro",JOptionPane.ERROR_MESSAGE,null);
            }

            if(forn.getCnpj()==null){
               JOptionPane.showMessageDialog(null,"CPNJ não cadastrado","Erro",JOptionPane.ERROR_MESSAGE,null);
            }else{
            JOptionPane.showMessageDialog(null,"Encontrado com sucesso!");

            conexaoBD bd = new conexaoBD();
            
            cnpj.setText(forn.getCnpj());
            nomeForn.setText(forn.getNome());
            ruaForn.setText(forn.getRua());
            bairroForn.setText(forn.getBairro());
            numeroForn.setText(forn.getNum());
            cepForn.setText(forn.getCep());
            tel1Forn.setText(forn.getTelefone1());
            tel2Forn.setText(forn.getTelefone2());
            razaoSocForn.setText(forn.getRazao());
            inscEst.setText(forn.getInscEstadual());
            cidadeForn.setText(forn.getFCidade());
            estadoForn.setText(forn.getFEstado().toString());
            }
         }
        
    }//GEN-LAST:event_consultarFornActionPerformed

    private void limparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCamposActionPerformed
        cnpj.setText("");
        nomeForn.setText("");
        ruaForn.setText("");
        bairroForn.setText("");
        numeroForn.setText("");
        cepForn.setText("");
        tel1Forn.setText("");
        tel2Forn.setText("");
        razaoSocForn.setText("");
        inscEst.setText("");
        cidadeForn.setText("");
        estadoForn.setText("");
    }//GEN-LAST:event_limparCamposActionPerformed

    private void cancelarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotaoActionPerformed
        alterarExcluirForn.this.dispose();
    }//GEN-LAST:event_cancelarBotaoActionPerformed

    private void excluirFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirFornActionPerformed
        conexaoBD cb = new conexaoBD();
        FornecedorDAO forn = null;

         
        try{
             
        if((cnpj.getText().equals(cnpj.getValue()))){ //Verifica se o campo está preenchido
           
                   
             int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o fornecedor?","Atenção",JOptionPane.YES_NO_OPTION);
             
             if(resposta == JOptionPane.YES_OPTION){
                cb.excluirFornecedor(cnpj.getText());
                        cnpj.setText("");
                        nomeForn.setText("");
                        ruaForn.setText("");
                        bairroForn.setText("");
                        numeroForn.setText("");
                        cepForn.setText("");
                        tel1Forn.setText("");
                        tel2Forn.setText("");
                        razaoSocForn.setText("");
                        inscEst.setText("");
                        cidadeForn.setText("");
                        estadoForn.setText("");
                JOptionPane.showMessageDialog(null, "Fornecedor excluído com sucesso!");
             }else{
                 if(resposta == JOptionPane.NO_OPTION){
                     //Somente fecha a caixa de pergunta.
                 }
             }
         }else{
            
         if((!cnpj.getText().equals(cnpj.getValue()))){
            JOptionPane.showMessageDialog(null, "Campo CNPJ vazio!","Erro ao excluir",JOptionPane.ERROR_MESSAGE,null);
            }
        }
            }
         catch(SQLException ex){
             JOptionPane.showMessageDialog(null, "Erro na exclusão do fornecedor!","Atenção",JOptionPane.ERROR_MESSAGE,null);
         }
    }//GEN-LAST:event_excluirFornActionPerformed

    private void alterarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFornActionPerformed
        String nome = nomeForn.getText();
        String razao = razaoSocForn.getText();
        String estadual = inscEst.getText();
        String cnpj1 = cnpj.getText();
        String rua = ruaForn.getText();
        String bairro = bairroForn.getText();
        String numero = numeroForn.getText();
        String cep = cepForn.getText();
        String cidade = cidadeForn.getText();
        String estado = estadoForn.getText();
        String tel1 = tel1Forn.getText();
        String tel2 = tel2Forn.getText();
        
        validaEntrada ve = new validaEntrada();
            /*Verifica se há campos obrig. vazios. Se não tiver, faz a inserção no BD.*/
            FornecedorDAO fornec = new FornecedorDAO(cnpj1,estadual,nome,razao,rua,bairro,cep,numero,cidade,estado,tel1,tel2);
       

                try{
                    fornec.atualizaFornecedor();      
                    JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
                }catch(entradaInvalidaException ex){
                    JOptionPane.showMessageDialog(null,""+ex.toString().substring(85,ex.toString().length()),"Erro",JOptionPane.ERROR_MESSAGE,null);
                }
        
    }//GEN-LAST:event_alterarFornActionPerformed

    private void razaoSocFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaoSocFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razaoSocFornActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           try{   
               javax.swing.UIManager um = new javax.swing.UIManager();
               um.setLookAndFeel(um.getSystemLookAndFeelClassName());
           }catch(Exception e){
               e.printStackTrace();
           }
           finally {
                new alterarExcluirForn().setVisible(true); //troque o nemo do frame!
            }
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarForn;
    private javax.swing.JTextField bairroForn;
    private javax.swing.JButton cancelarBotao;
    private javax.swing.JFormattedTextField cepForn;
    private javax.swing.JTextField cidadeForn;
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JButton consultarForn;
    private javax.swing.JTextField estadoForn;
    private javax.swing.JButton excluirForn;
    private javax.swing.JTextField inscEst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton limparCampos;
    private javax.swing.JTextField nomeForn;
    private javax.swing.JTextField numeroForn;
    private javax.swing.JTextField razaoSocForn;
    private javax.swing.JTextField ruaForn;
    private javax.swing.JFormattedTextField tel1Forn;
    private javax.swing.JFormattedTextField tel2Forn;
    // End of variables declaration//GEN-END:variables
}
