/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.contacteditor;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import my.contacteditor.conexao.conexaoBD;

/**
 *
 * @author  Lucas Tassi
 *          Lucas Diniz
 *          Lucas Barbosa
 *          Jhordan Garcia
 */
public class alterarExcluirCliente extends javax.swing.JFrame {
    
    /**
     * Creates new form alterarExcluirCliente
     */
    public alterarExcluirCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tel2Cliente = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bairroCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numeroCliente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        cnpjCliente = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        ruaCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cepCliente = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tel1Cliente = new javax.swing.JFormattedTextField();
        consultarCliente = new javax.swing.JButton();
        limparCampos = new javax.swing.JButton();
        cancelarBotao = new javax.swing.JButton();
        excluirCliente = new javax.swing.JButton();
        alterarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        razaoSocCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        inscEstCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        estadoCliente = new javax.swing.JTextField();
        cidadeCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel6.setText("*Rua");

        try {
            tel2Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("*Número");

        jLabel8.setText("Bairro");

        jLabel9.setText("CEP");

        numeroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroClienteActionPerformed(evt);
            }
        });

        jLabel10.setText("Telefone 2");

        try {
            cnpjCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpjCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjActionPerformed(evt);
            }
        });

        jLabel1.setText("*Nome Fantasia:  ");

        nomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteActionPerformed(evt);
            }
        });

        ruaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("*Telefone 1");

        jLabel4.setText("*CNPJ:");

        try {
            cepCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tel1Cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tel1Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel1ClienteActionPerformed(evt);
            }
        });

        consultarCliente.setText("Consultar");
        consultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClienteActionPerformed(evt);
            }
        });

        limparCampos.setText("Limpar");
        limparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCamposActionPerformed(evt);
            }
        });

        cancelarBotao.setText("Cancelar");
        cancelarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotaoActionPerformed(evt);
            }
        });

        excluirCliente.setText("Excluir");
        excluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClienteActionPerformed(evt);
            }
        });

        alterarCliente.setText("Alterar ");
        alterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("CONSULTA DE CLIENTE");

        jLabel5.setText("*Razão Social:");

        razaoSocCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaoSocClienteActionPerformed(evt);
            }
        });

        jLabel11.setText("*Insc. Est.:");

        jLabel12.setText("*Cidade");

        jLabel13.setText("*Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                        .addComponent(alterarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarBotao)
                        .addGap(16, 16, 16))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ruaCliente)
                                    .addComponent(bairroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(cidadeCliente))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numeroCliente)
                                    .addComponent(cepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tel1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tel2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(cnpjCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparCampos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(razaoSocCliente)
                            .addComponent(inscEstCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpjCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(consultarCliente)
                    .addComponent(limparCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(razaoSocCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inscEstCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(numeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(estadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(tel1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBotao)
                    .addComponent(excluirCliente)
                    .addComponent(alterarCliente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void numeroClienteActionPerformed(java.awt.event.ActionEvent evt) {                                           
     
    }                                          

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {                                     
       
    }                                    

    private void nomeClienteActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
    }                                        

    private void ruaClienteActionPerformed(java.awt.event.ActionEvent evt) {                                        
       
    }                                       

    private void tel1ClienteActionPerformed(java.awt.event.ActionEvent evt) {                                         

    }                                        

    private void consultarClienteActionPerformed(java.awt.event.ActionEvent evt) {                                              
        conexaoBD cb = new conexaoBD();
        ClienteDAO cliente = null;
        
        
         if(!cnpjCliente.getText().equals(cnpjCliente.getValue())){
            JOptionPane.showMessageDialog(null,"Campo não pode ser vazio!","Erro",JOptionPane.ERROR_MESSAGE,null);
        }else{

            try{
                cliente = cb.consultarCliente(cnpjCliente.getText());
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"CPNJ não cadastrado","Erro",JOptionPane.ERROR_MESSAGE,null);
            }

            if(cliente.getCnpj()==null){
               JOptionPane.showMessageDialog(null,"CPNJ não cadastrado","Erro",JOptionPane.ERROR_MESSAGE,null);
            }else{
            JOptionPane.showMessageDialog(null,"Encontrado com sucesso!");

            conexaoBD bd = new conexaoBD();
            
            cnpjCliente.setText(cliente.getCnpj());
            nomeCliente.setText(cliente.getNome());
            ruaCliente.setText(cliente.getRua());
            bairroCliente.setText(cliente.getBairro());
            numeroCliente.setText(cliente.getNum());
            cepCliente.setText(cliente.getCep());
            tel1Cliente.setText(cliente.getTelefone1());
            tel2Cliente.setText(cliente.getTelefone2());
            razaoSocCliente.setText(cliente.getRazao());
            inscEstCliente.setText(cliente.getInscEstadual());
            cidadeCliente.setText(cliente.getCCidade());
            estadoCliente.setText(cliente.getCEstado().toString());
            }
         }
        
    }                                             

    private void limparCamposActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cnpjCliente.setText("");
        nomeCliente.setText("");
        ruaCliente.setText("");
        bairroCliente.setText("");
        numeroCliente.setText("");
        cepCliente.setText("");
        tel1Cliente.setText("");
        tel2Cliente.setText("");
        razaoSocCliente.setText("");
        inscEstCliente.setText("");
        cidadeCliente.setText("");
        estadoCliente.setText("");
    }                                            

    private void cancelarBotaoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        alterarExcluirCliente.this.dispose();
    }                                             

    private void excluirClienteActionPerformed(java.awt.event.ActionEvent evt) {                                            
        conexaoBD cb = new conexaoBD();
        ClienteDAO cliente = null;

         
        try{
             
        if((cnpjCliente.getText().equals(cnpjCliente.getValue()))){ //Verifica se o campo está preenchido
           
                   
             int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o cliente?","Atenção",JOptionPane.YES_NO_OPTION);
             
             if(resposta == JOptionPane.YES_OPTION){
                cb.excluirCliente(cnpjCliente.getText());
                        cnpjCliente.setText("");
                        nomeCliente.setText("");
                        ruaCliente.setText("");
                        bairroCliente.setText("");
                        numeroCliente.setText("");
                        cepCliente.setText("");
                        tel1Cliente.setText("");
                        tel2Cliente.setText("");
                        razaoSocCliente.setText("");
                        inscEstCliente.setText("");
                        cidadeCliente.setText("");
                        estadoCliente.setText("");
                JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso!");
             }else{
                 if(resposta == JOptionPane.NO_OPTION){
                     //Somente fecha a caixa de pergunta.
                 }
             }
         }else{
            
         if((!cnpjCliente.getText().equals(cnpjCliente.getValue()))){
            JOptionPane.showMessageDialog(null, "Campo CNPJ vazio!","Erro ao excluir",JOptionPane.ERROR_MESSAGE,null);
            }
        }
            }
         catch(SQLException ex){
             JOptionPane.showMessageDialog(null, "Erro na exclusão do cliente!","Atenção",JOptionPane.ERROR_MESSAGE,null);
         }
    }                                           

    private void alterarClienteActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String nome = nomeCliente.getText();
        String razao = razaoSocCliente.getText();
        String estadual = inscEstCliente.getText();
        String cnpj1 = cnpjCliente.getText();
        String rua = ruaCliente.getText();
        String bairro = bairroCliente.getText();
        String numero = numeroCliente.getText();
        String cep = cepCliente.getText();
        String cidade = cidadeCliente.getText();
        String estado = estadoCliente.getText();
        String tel1 = tel1Cliente.getText();
        String tel2 = tel2Cliente.getText();
        
        validaEntrada ve = new validaEntrada();
            /*Verifica se há campos obrig. vazios. Se não tiver, faz a inserção no BD.*/
            ClienteDAO cli = new ClienteDAO(cnpj1,estadual,nome,razao,rua,bairro,cep,numero,cidade,estado,tel1,tel2);
       

                try{
                    cli.atualizaCliente();      
                    JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
                }catch(entradaInvalidaException ex){
                    JOptionPane.showMessageDialog(null,""+ex.toString().substring(85,ex.toString().length()),"Erro",JOptionPane.ERROR_MESSAGE,null);
                }
        
    }                                           

    private void razaoSocClienteActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           try{   
               javax.swing.UIManager um = new javax.swing.UIManager();
               um.setLookAndFeel(um.getSystemLookAndFeelClassName());
           }catch(Exception e){
               e.printStackTrace();
           }
           finally {
                new alterarExcluirCliente().setVisible(true); //troque o nemo do frame!
            }
            }
        });
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton alterarCliente;
    private javax.swing.JTextField bairroCliente;
    private javax.swing.JButton cancelarBotao;
    private javax.swing.JFormattedTextField cepCliente;
    private javax.swing.JTextField cidadeCliente;
    private javax.swing.JFormattedTextField cnpjCliente;
    private javax.swing.JButton consultarCliente;
    private javax.swing.JTextField estadoCliente;
    private javax.swing.JButton excluirCliente;
    private javax.swing.JTextField inscEstCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton limparCampos;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField numeroCliente;
    private javax.swing.JTextField razaoSocCliente;
    private javax.swing.JTextField ruaCliente;
    private javax.swing.JFormattedTextField tel1Cliente;
    private javax.swing.JFormattedTextField tel2Cliente;
    // End of variables declaration                   
}
