/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.contacteditor;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import my.contacteditor.conexao.conexaoBD;

/**
 *
 * @author lucas
 */
public class cadastroProdutos extends javax.swing.JFrame {

    int verificaSeEhAlteracao = 0;
    
    /**
     * Creates new form Produtos
     */
    public cadastroProdutos() {
        initComponents();
                
        POutros.setEditable(false);
        POutros.setBackground(Color.LIGHT_GRAY);
        Pnome.setDocument(new UpperCase());
        Pdesc.setDocument(new UpperCase());
        PDescRed.setDocument(new UpperCase());
        PlocalEstoque.setDocument(new UpperCase());
        POutros.setDocument(new UpperCase());
        PObs.setDocument(new UpperCase());
        
    }
    
        public void preencheCampos(){
        conexaoBD cb = new conexaoBD();
        ProdutoDAO p = null;
        
        try{
            p = cb.consultarProduto(PCodigo.getText());
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Produto não cadastrado","Erro",JOptionPane.ERROR_MESSAGE,null);
        }   
            
        if(p.getCodigo()==0){
           JOptionPane.showMessageDialog(null,"Produto "+PCodigo.getText()+"não cadastrado","Erro",JOptionPane.ERROR_MESSAGE,null); 
        }else{

            PCodigo.setText(Integer.toString(p.getCodigo()));
            Pnome.setText(p.getNome());
            PCodBarras.setText(p.getCodBarras());
            Pdesc.setText(p.getDescricao());
            PDescRed.setText(p.getDescricaoReduzida());
            PlocalEstoque.setText(p.getLocalEstoque());
            PUnVenda.setSelectedItem(p.getUnCompra());
            PEstoque.setText(Integer.toString(p.getEstoqueInicial()));
            PCusto.setText(Float.toString(p.getCusto()));
            PTributos.setText(Float.toString(p.getTributos()));
            PFabricante.setSelectedItem(p.getFabricante());
            POutros.setText(p.getOutros());
            Pcateg.setSelectedItem(p.getCategoria());
            PFab.setText(p.getDataFab());
            PVal.setText(p.getDataVal());
            PObs.setText(p.getObservacoes());
  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Pnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PFabricante = new javax.swing.JComboBox<>();
        PDescRed = new javax.swing.JTextField();
        Pdesc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PUnVenda = new javax.swing.JComboBox<>();
        PlocalEstoque = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PEstoque = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Pcateg = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        PCusto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PTributos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PCodBarras = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PObs = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        POutros = new javax.swing.JTextField();
        PFab = new javax.swing.JFormattedTextField();
        PVal = new javax.swing.JFormattedTextField();

        jToggleButton1.setText("jToggleButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Cadastro de Produtos");

        jLabel2.setText("Nome:");

        Pnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Código:");

        PCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCodigoActionPerformed(evt);
            }
        });

        jLabel4.setText("Descrição:");

        jLabel5.setText("Desc. Reduzida:");

        jLabel6.setText("Fabricante:");

        PFabricante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amazon Beer", "AmBev", "Baden Baden (cervejaria)", "Bohemia (cerveja)", "Brasil Kirin", "Cervejaria Canoinhense", "Casa di Conti", "Cerpa", "Cervejaria Abadessa", "Cervejaria Wäls", "Companhia Brasileira de Bebidas Premium", "Eisenbahn", "Grupo Imperial", "Grupo Petrópolis", "________________________________", " ", "Água da Serra", "AmBev", "Bellpar", "Brasil Kirin", "Coca-Cola Norsa", "Companhia Müller de Bebidas", "Cutrale", "Dolly (refrigerante)", "Dore", "Ferráspari", "Fruki", "Funada", "Golé", "Renosa", "Grupo São Geraldo", "Anheuser-Busch InBev", "Lista de marcas de refrigerantes do Brasil", "Poá (água mineral)", "RC Cola", "Recofarma", "Refrigerantes Marajá", "Solar Refrescos", "Outros" }));
        PFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PFabricanteActionPerformed(evt);
            }
        });

        jLabel7.setText("Local do Estoque:");

        jLabel8.setText("Un. de Venda:");

        PUnVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG – Quilograma", "LT – Litro", "UN – Unidade", "MT – Metro linear", "M2 – Metro quadrado", "M3 – Metro cúbico", "PR – Par" }));
        PUnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUnVendaActionPerformed(evt);
            }
        });

        jLabel10.setText("Estoque inicial:");

        jLabel11.setText("Categoria:");

        Pcateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida Alcoólica", "Bebida não Alcoólica", "Achocolatado", "Água potável", "Bebidas de soja", "Bebidas energética", "Bebidas esportiva", "Bebidas fria", "Bebidas quente", "Cachaça", "Café ", "Cerveja", "Chá", "Coquetel", "Refrigerante", "Rum", "Sumo", "Suco", "Whisky", "Vodka" }));

        jLabel12.setText("Custo:");

        PCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCustoActionPerformed(evt);
            }
        });

        jLabel13.setText("Tributos (%):");

        jLabel14.setText("Cód. de Barras:");

        jLabel15.setText("Data Fabricação:");

        jLabel16.setText("Data de Validade:");

        PObs.setColumns(20);
        PObs.setRows(5);
        jScrollPane2.setViewportView(PObs);

        jLabel17.setText("Observações:");

        jButton1.setText("Incluir Produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        try {
            PFab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            PVal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(PUnVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(PEstoque)
                                                .addComponent(PCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel13)))
                                    .addGap(12, 12, 12)
                                    .addComponent(PTributos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2))
                                            .addGap(74, 74, 74)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Pnome, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4))
                                            .addGap(27, 27, 27)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Pdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PDescRed, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(PlocalEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel14))
                                            .addGap(28, 28, 28)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Pcateg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(POutros)
                                                .addComponent(PFabricante, 0, 301, Short.MAX_VALUE)
                                                .addComponent(PCodBarras)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(PFab, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel16)
                                            .addGap(4, 4, 4)
                                            .addComponent(PVal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel17))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(PCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Pnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(PFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Pdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(POutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PDescRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Pcateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PlocalEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(PFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PUnVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(PEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(PCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(PTributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConsultaProdutos cp = new ConsultaProdutos();
        
        int codigo = Integer.parseInt(PCodigo.getText());
        String nome = Pnome.getText();
        String codBarras = PCodBarras.getText();
        String descricao = Pdesc.getText();
        String descReduzida = PDescRed.getText();
        String localEstoque = PlocalEstoque.getText();
        String unVenda = PUnVenda.getSelectedItem().toString();
        int estoque = Integer.parseInt(PEstoque.getText());
        float custo = Float.parseFloat(PCusto.getText().replace(",", "."));
        float tributos = Float.parseFloat(PTributos.getText().replace(",", "."));
        String fabricante = PFabricante.getSelectedItem().toString();
        String outros = POutros.getText();
        String categoria = Pcateg.getSelectedItem().toString();
        String dataFabricacao = PFab.getText();
        String dataValidade = PVal.getText();
        String observacao = PObs.getText();    
        
        ProdutoDAO prod = new ProdutoDAO(codigo, nome, descricao, descReduzida, codBarras,
                                         localEstoque, fabricante, categoria, dataFabricacao,
                                         dataValidade, unVenda, estoque, custo, tributos, observacao, outros);

        if(verificaSeEhAlteracao==0){
            try{
                prod.insereProduto();
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                        //dispose();               
                }catch(entradaInvalidaException ex){
                    JOptionPane.showMessageDialog(null,""+ex.toString().substring(85,ex.toString().length()),"Erro",JOptionPane.ERROR_MESSAGE,null);
                }catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,""+ex,"Erro",JOptionPane.ERROR_MESSAGE,null);
                }
        }else{
            if(verificaSeEhAlteracao==1){
                
             try{
                prod.atualizaProduto();
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                        //dispose();               
                }catch(entradaInvalidaException ex){
                    JOptionPane.showMessageDialog(null,""+ex.toString().substring(85,ex.toString().length()),"Erro",JOptionPane.ERROR_MESSAGE,null);
                }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCodigoActionPerformed

    private void PUnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUnVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PUnVendaActionPerformed

    private void PFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PFabricanteActionPerformed
           
        if(PFabricante.getSelectedItem().equals("Outros")){
            POutros.setEditable(true);
            POutros.setBackground(Color.WHITE);
        }
        
        if(!PFabricante.getSelectedItem().equals("Outros")){
            POutros.setEditable(false);
            POutros.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_PFabricanteActionPerformed

    private void PnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnomeActionPerformed
        Pnome.setText(Pnome.getText().toUpperCase());  
    }//GEN-LAST:event_PnomeActionPerformed

    private void PCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCustoActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           try{   
               javax.swing.UIManager um = new javax.swing.UIManager();
               um.setLookAndFeel(um.getSystemLookAndFeelClassName());
           }catch(Exception e){
               e.printStackTrace();
           }
           finally {
                new cadastroProdutos().setVisible(true); //troque o nemo do frame!
            }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PCodBarras;
    public javax.swing.JTextField PCodigo;
    private javax.swing.JTextField PCusto;
    private javax.swing.JTextField PDescRed;
    private javax.swing.JTextField PEstoque;
    private javax.swing.JFormattedTextField PFab;
    private javax.swing.JComboBox<String> PFabricante;
    private javax.swing.JTextArea PObs;
    private javax.swing.JTextField POutros;
    private javax.swing.JTextField PTributos;
    private javax.swing.JComboBox<String> PUnVenda;
    private javax.swing.JFormattedTextField PVal;
    private javax.swing.JComboBox<String> Pcateg;
    private javax.swing.JTextField Pdesc;
    private javax.swing.JTextField PlocalEstoque;
    private javax.swing.JTextField Pnome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
