/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.contacteditor;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import my.contacteditor.conexao.conexaoBD;

/**
 *
 * @author Lucas A
 */
public class ConsultarHistorico extends javax.swing.JFrame {

     public String informacaoTabelaCodigo;
    
    /**
     * Creates new form ConsultarHistorico
     */
    public ConsultarHistorico() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();
        tabelaConsulta.setRowSorter(new TableRowSorter(modelo));

    }
    
    public String info(){
        int linha = tabelaConsulta.getSelectedRow();
        String info = tabelaConsulta.getModel().getValueAt(linha, 0).toString();
        
        return info;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Numerodacompra = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsulta = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(794, 420));

        jLabel1.setText("HISTÓRICO DE COMPRAS");

        jLabel2.setText("Número da Compra:");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar Todas as Compras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm. Compra", "Data Compra", "Cód. Produto", "Nome Produto", "Quantidade", "Nome Fornecedor"
            }
        ));
        tabelaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaConsulta);

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(Numerodacompra, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Numerodacompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<HistoricoDAO> p = new ArrayList<HistoricoDAO>();
        conexaoBD cb = new conexaoBD();
        try{
        p = (ArrayList<HistoricoDAO>) cb.consultarHistoricosCODIGO(Numerodacompra.getText());
        }catch(SQLException ex){
             Logger.getLogger(ConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(p.isEmpty()){
                JOptionPane.showMessageDialog(null, "Banco de Dados Vazio!");
                return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();
        
         modelo.setNumRows(0);
            
        Object[] fila = new Object[modelo.getColumnCount()];
            for(int i=0; i < p.size(); i++){
                modelo.addRow(new Object[]{
                    p.get(i).getHcodigo(),
                    p.get(i).getData(),
                    p.get(i).getPCod(),
                    p.get(i).getPNome(),
                    p.get(i).getQuantidade(),
                    p.get(i).getFNome()
                });
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<HistoricoDAO> p = new ArrayList<HistoricoDAO>();
        conexaoBD cb = new conexaoBD();
        
        try{
            p = (ArrayList<HistoricoDAO>) cb.consultaTodosHistoricos();
        }catch (SQLException ex) {
            Logger.getLogger(ConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(p.isEmpty()){
            JOptionPane.showMessageDialog(null, "Banco de Dados Vazio!");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();
        
         modelo.setNumRows(0);
            
        Object[] fila = new Object[modelo.getColumnCount()];
            for(int i=0; i < p.size(); i++){
                modelo.addRow(new Object[]{
                    p.get(i).getHcodigo(),
                    p.get(i).getData(),
                    p.get(i).getPCod(),
                    p.get(i).getPNome(),
                    p.get(i).getQuantidade(),
                    p.get(i).getFNome()
                });
                
            }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        conexaoBD cb = new conexaoBD();
        HistoricoDAO p = null;

         
        try{
                
             int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o histórico selecionado?","Atenção",JOptionPane.YES_NO_OPTION);
             
             if(resposta == JOptionPane.YES_OPTION){
                 
                String info = info();

                cb.excluirHistorico(info);
                JOptionPane.showMessageDialog(null, "Histórico excluído com sucesso!");
                
                DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();
                modelo.setNumRows(0);
                
             }else{
                 if(resposta == JOptionPane.NO_OPTION){
                     //Somente fecha a caixa de pergunta.
                 }
             }
         
            }
         catch(Exception ex){
             JOptionPane.showMessageDialog(null, "Erro na exclusão!","Atenção",JOptionPane.ERROR_MESSAGE,null);
         }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabelaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaMouseClicked
        informacaoTabelaCodigo = info(); //Pega o código do produto para realiza a busca no sistema e prrencher a tela de alteração.
        System.out.println("INFO: "+informacaoTabelaCodigo);
    }//GEN-LAST:event_tabelaConsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Numerodacompra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaConsulta;
    // End of variables declaration//GEN-END:variables
}
