/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.contacteditor;

import java.awt.Color;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import my.contacteditor.conexao.conexaoBD;

/**
 *
 * @author lucas
 */
public class ConsultaProdutos extends javax.swing.JFrame {

    public String informacaoTabelaCodigo;
    public float custo, tributos;
    float precoProduto;
    NumberFormat formatter = new DecimalFormat(".00");
  
    /**
     * Creates new form ConsultarExcluir
     */
    public ConsultaProdutos() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();
        tabelaConsulta.setRowSorter(new TableRowSorter(modelo));
        comboOpcao.setSelectedItem("Descrição");
        
        pesquisaGeral.setDocument(new UpperCase());
    }

    //Pega o CPF na Tabela
    public String info(){
        int linha = tabelaConsulta.getSelectedRow();
        String info = tabelaConsulta.getModel().getValueAt(linha, 0).toString();
        
        return info;
    }
    
    public String Custo(){
        int linha = tabelaConsulta.getSelectedRow();
        String info = tabelaConsulta.getModel().getValueAt(linha, 4).toString();
        
        return info;
    }
    
    public String Tributos(){
        int linha = tabelaConsulta.getSelectedRow();
        String info = tabelaConsulta.getModel().getValueAt(linha, 5).toString();
        
        return info;
    }
    
    public float precoProduto(){
        custo = Float.parseFloat(Custo());
        tributos = Float.parseFloat(Tributos()); //Captura os valores de custo e tributo para imprimir para o usuário.
        
        precoProduto = custo + (custo*(tributos/100)); // Faz o calculo do proço final.
        
        return precoProduto;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpf = new javax.swing.JFormattedTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        comboOpcao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsulta = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        produtoCodigo = new javax.swing.JTextField();
        pesquisaGeral = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valorTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tributosTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tributosFinal = new javax.swing.JLabel();

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Mostrar Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        comboOpcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Descrição", "Código" }));
        comboOpcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOpcaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Procurar por:");

        tabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Descrição", "Fabricante", "Custo (R$)", "Tributos (%)"
            }
        ));
        tabelaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaConsulta);

        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("CONSULTA DE PRODUTOS");

        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        pesquisaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaGeralActionPerformed(evt);
            }
        });

        jLabel3.setText("Preço");

        valorTotal.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        valorTotal.setForeground(new java.awt.Color(254, 9, 9));

        jLabel5.setText("Tributos:");

        tributosTotal.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tributosFinal.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        tributosFinal.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pesquisaGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(produtoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tributosFinal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tributosTotal)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(produtoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesquisaGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tributosFinal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tributosTotal))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            ArrayList<ProdutoDAO> p = new ArrayList<ProdutoDAO>();
            conexaoBD cb = new conexaoBD();
            
            try{
                p = (ArrayList<ProdutoDAO>) cb.consultaTodosProdutos();
            } catch (SQLException ex) {
            
                Logger.getLogger(ConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(p.isEmpty()){
                JOptionPane.showMessageDialog(null, "Banco de Dados Vazio!");
                return;
            }
            
            DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();
            
            modelo.setNumRows(0);
            
            Object[] fila = new Object[modelo.getColumnCount()];
            for(int i=0; i < p.size(); i++){
                modelo.addRow(new Object[]{
                    p.get(i).getCodigo(),
                    p.get(i).getNome(),
                    p.get(i).getDescricaoReduzida(),
                    p.get(i).getFabricante(),
                    p.get(i).getCusto(),
                    p.get(i).getTributos()
                });
                
            }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed

    }//GEN-LAST:event_cpfActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArrayList<ProdutoDAO> p = new ArrayList<ProdutoDAO>();
            conexaoBD cb = new conexaoBD();
            
            try{
                
                if(comboOpcao.getSelectedItem().equals("Descrição")){
                    p = (ArrayList<ProdutoDAO>) cb.consultaTodosProdutosPorNome(pesquisaGeral.getText());
                    System.out.println("ASD: "+pesquisaGeral.getText());
                }else{
                    if(comboOpcao.getSelectedItem().equals("Código")){
                        p = (ArrayList<ProdutoDAO>) cb.consultaTodosProdutosPorCodigo(produtoCodigo.getText());
                        System.out.println("ASD: "+pesquisaGeral.getText());
                    }
                }
            } catch (SQLException ex) {
            
                Logger.getLogger(ConsultaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(p.isEmpty()){
                JOptionPane.showMessageDialog(null, "Banco de Dados Vazio!");
                return;
            }
            
            DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();
            
            modelo.setNumRows(0);
            
            Object[] fila = new Object[modelo.getColumnCount()];
            for(int i=0; i < p.size(); i++){
                modelo.addRow(new Object[]{
                    p.get(i).getCodigo(),
                    p.get(i).getNome(),
                    p.get(i).getDescricaoReduzida(),
                    p.get(i).getFabricante(),
                    p.get(i).getCusto(),
                    p.get(i).getTributos()
                });
                
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboOpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOpcaoActionPerformed
       
        if(comboOpcao.getSelectedItem().equals("Descrição")){
            produtoCodigo.setEditable(false);
            produtoCodigo.setBackground(Color.GRAY);
            pesquisaGeral.setEditable(true);
            pesquisaGeral.setBackground(Color.WHITE);
        }else{
            if(comboOpcao.getSelectedItem().equals("Código")){
                produtoCodigo.setEditable(true);
                produtoCodigo.setBackground(Color.WHITE);
                pesquisaGeral.setEditable(false);
                pesquisaGeral.setBackground(Color.GRAY);
            }
        }
    }//GEN-LAST:event_comboOpcaoActionPerformed

    private void tabelaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaMouseClicked
        informacaoTabelaCodigo = info(); //Pega o código do produto para realiza a busca no sistema e prrencher a tela de alteração.
        System.out.println("INFO: "+informacaoTabelaCodigo);
        
        valorTotal.setText("R$ "+formatter.format(precoProduto()));
        tributosFinal.setText(""+Tributos()+" %");  
    }//GEN-LAST:event_tabelaConsultaMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        conexaoBD cb = new conexaoBD();
        ProdutoDAO p = null;

         
        try{
                
             int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o produto selecionado?","Atenção",JOptionPane.YES_NO_OPTION);
             
             if(resposta == JOptionPane.YES_OPTION){
                 
                String info = info();

                cb.excluirProduto(info);
                JOptionPane.showMessageDialog(null, "Produto excluído com sucesso!");
                
                DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();
                modelo.setNumRows(0);
                
             }else{
                 if(resposta == JOptionPane.NO_OPTION){
                     //Somente fecha a caixa de pergunta.
                 }
             }
         
            }
         catch(Exception ex){
             JOptionPane.showMessageDialog(null, "Erro na exclusão!","Atenção",JOptionPane.ERROR_MESSAGE,null);
         }
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cadastroProdutos ac = new cadastroProdutos();
        ac.verificaSeEhAlteracao = 1;
        //Nessa parte, o campo CPF de alterarCandidato é preenchido com o CPF escolhido da tabela. Logo depois, o sistema 
        //preenche a interface com os dados necessários e em seguida mostra para o usuário.
        ac.PCodigo.setText(informacaoTabelaCodigo);
        ac.preencheCampos();
        
        ac.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void pesquisaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaGeralActionPerformed
        
    }//GEN-LAST:event_pesquisaGeralActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           try{   
               javax.swing.UIManager um = new javax.swing.UIManager();
               um.setLookAndFeel(um.getSystemLookAndFeelClassName());
           }catch(Exception e){
               e.printStackTrace();
           }
           finally {
                new ConsultaProdutos().setVisible(true); //troque o nemo do frame!
            }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboOpcao;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pesquisaGeral;
    private javax.swing.JTextField produtoCodigo;
    private javax.swing.JTable tabelaConsulta;
    private javax.swing.JLabel tributosFinal;
    private javax.swing.JLabel tributosTotal;
    private javax.swing.JLabel valorTotal;
    // End of variables declaration//GEN-END:variables


}
