/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.contacteditor;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import my.contacteditor.conexao.conexaoBD;

/**
 *
 * @author Lucas
 */
public class ConsultaPedidos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPedidos
     */
    public ConsultaPedidos() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();
        tabelaConsulta.setRowSorter(new TableRowSorter(modelo));
    }
    
    public String info(){
        int linha = tabelaConsulta.getSelectedRow();
        String info = tabelaConsulta.getModel().getValueAt(linha, 0).toString();
        
        return info;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaConsulta = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CONSULTA DE PEDIDOS");

        jLabel2.setText("Código");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar Todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Valor", "Data Entrega", "Pago"
            }
        ));
        jScrollPane2.setViewportView(tabelaConsulta);

        jScrollPane1.setViewportView(jScrollPane2);

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(135, 135, 135))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<PedidoDAO> p = new ArrayList<PedidoDAO>();
        conexaoBD cb = new conexaoBD();

        try{
            p = (ArrayList<PedidoDAO>) cb.consultarPedido(codigo.getText());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (p.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Pedido nao existe!");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();

        modelo.setNumRows(0);

        Object[] fila = new Object[modelo.getColumnCount()];
        for(int i=0; i < p.size(); i++){
            modelo.addRow(new Object[]{
                p.get(i).getCodigo(),
                p.get(i).getValor(),
                p.get(i).getDataEntrega(),
                p.get(i).getPago()
            });

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<PedidoDAO> p = new ArrayList<PedidoDAO>();
        conexaoBD cb = new conexaoBD();

        try{
            p = (ArrayList<PedidoDAO>) cb.consultarTodosPedidos(codigo.getText());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (p.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Banco vazio!");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();

        modelo.setNumRows(0);

        Object[] fila = new Object[modelo.getColumnCount()];
        for(int i=0; i < p.size(); i++){
            modelo.addRow(new Object[]{
                p.get(i).getCodigo(),
                p.get(i).getValor(),
                p.get(i).getDataEntrega(),
                p.get(i).getPago()
            });

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        conexaoBD cb = new conexaoBD();
         
        try{
                
             int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o pedido selecionado?","Atenção",JOptionPane.YES_NO_OPTION);
             
             if(resposta == JOptionPane.YES_OPTION){
                 
                String info = info();

                cb.excluirPedido(info);
                JOptionPane.showMessageDialog(null, "Pedido excluído com sucesso!");
                
                DefaultTableModel modelo = (DefaultTableModel) tabelaConsulta.getModel();
                modelo.setNumRows(0);
                
             }else{
                 if(resposta == JOptionPane.NO_OPTION){
                     //Somente fecha a caixa de pergunta.
                 }
             }
         
            }
         catch(Exception ex){
             JOptionPane.showMessageDialog(null, "Erro na exclusão!","Atenção",JOptionPane.ERROR_MESSAGE,null);
         }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      
                                     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           try{   
               javax.swing.UIManager um = new javax.swing.UIManager();
               um.setLookAndFeel(um.getSystemLookAndFeelClassName());
           }catch(Exception e){
               e.printStackTrace();
           }
           finally {
                new ConsultaPedidos().setVisible(true); //troque o nemo do frame!
            }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaConsulta;
    // End of variables declaration//GEN-END:variables
}
