/*

 */
package my.contacteditor;

import javax.swing.JFrame;
import my.contacteditor.FornecedorDAO.*;
import javax.swing.JOptionPane;
import my.contacteditor.conexao.conexaoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  Lucas Tassi
 *          Lucas Diniz
 *          Lucas Barbosa
 *          Jhordan Garcia
 */
public class TelaFornCadastro extends javax.swing.JFrame {

    conexaoBD forn = new conexaoBD();
    /**
     * Creates new form TelaFornCadastro
     */
    public TelaFornCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        nomeForn = new javax.swing.JTextField();
        ruaForn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cadastrarForn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bairroForn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numeroForn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cnpj = new javax.swing.JFormattedTextField();
        cepForn = new javax.swing.JFormattedTextField();
        tel1Forn = new javax.swing.JFormattedTextField();
        tel2Forn = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        razaoSocForn = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        inscEst = new javax.swing.JTextField();
        estadoForn = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cidadeForn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("*Nome Fantasia: ");

        nomeForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFornActionPerformed(evt);
            }
        });

        ruaForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaFornActionPerformed(evt);
            }
        });

        jLabel3.setText("*Telefone 1:");

        jLabel4.setText("*CNPJ:");

        cadastrarForn.setText("Cadastrar");
        cadastrarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFornActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("*Rua:");

        jLabel7.setText("*Número:");

        jLabel8.setText("Bairro:");

        jLabel9.setText("CEP:");

        numeroForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFornActionPerformed(evt);
            }
        });

        jLabel10.setText("Telefone 2:");

        try {
            cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjActionPerformed(evt);
            }
        });

        try {
            cepForn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cepForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepFornActionPerformed(evt);
            }
        });

        try {
            tel1Forn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tel1Forn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel1FornActionPerformed(evt);
            }
        });

        try {
            tel2Forn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("*Campos obrigatórios");

        jLabel11.setText("CADASTRO DE FORNECEDOR");

        jLabel12.setText("*Razão Social:");

        razaoSocForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaoSocFornActionPerformed(evt);
            }
        });

        jLabel13.setText("*Insc. Est.:");

        inscEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscEstActionPerformed(evt);
            }
        });

        estadoForn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC ", "AL", "AP", "AM", "BA", "CE", "DF ", "ES", "GO", "MA", "MT", "MS", "MG ", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR ", "SC", "SP", "SE", "TO" }));
        estadoForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoFornActionPerformed(evt);
            }
        });

        jLabel14.setText("*Estado:");

        jLabel15.setText("*Cidade");

        cidadeForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeFornActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)))
                        .addGap(4, 4, 4)
                        .addComponent(inscEst, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(razaoSocForn)
                            .addComponent(nomeForn))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel8))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bairroForn, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cidadeForn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(ruaForn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel15))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroForn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cepForn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadoForn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarForn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(tel1Forn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addComponent(tel2Forn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addComponent(inscEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(razaoSocForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(numeroForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cepForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(bairroForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(estadoForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(cidadeForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(tel1Forn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tel2Forn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadastrarForn)
                            .addComponent(jButton2)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFornActionPerformed
        String nome = nomeForn.getText();
        String cnpj1 = cnpj.getText();
        String rua = ruaForn.getText();
        String bairro = bairroForn.getText();
        String numero = numeroForn.getText();
        String cep = cepForn.getText();
        String tel1 = tel1Forn.getText();
        String tel2 = tel2Forn.getText();
        String insEst = inscEst.getText();
        String razSocial = razaoSocForn.getText();
        String cidade = cidadeForn.getText();
        String estado = estadoForn.getSelectedItem().toString();
    
            /*Verifica se há campos obr. vazios. Se não tiver, faz a inserção no BD.*/
        FornecedorDAO fornec = new FornecedorDAO(cnpj1,insEst,nome,razSocial,rua,bairro,cep,numero,cidade,estado,tel1,tel2);


                try{
                    fornec.insereFornecedor();
                    JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                    //dispose();               
                }catch(entradaInvalidaException ex){
                    JOptionPane.showMessageDialog(null,""+ex.toString().substring(85,ex.toString().length()),"Erro",JOptionPane.ERROR_MESSAGE,null);
                }catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,""+ex,"Erro",JOptionPane.ERROR_MESSAGE,null);
            }
        
    }//GEN-LAST:event_cadastrarFornActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       TelaFornCadastro.this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tel1FornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel1FornActionPerformed

    }//GEN-LAST:event_tel1FornActionPerformed

    private void ruaFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaFornActionPerformed
        if(ruaForn.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Rua - Preenchimento obrigatório!");
        }
    }//GEN-LAST:event_ruaFornActionPerformed

    private void nomeFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFornActionPerformed
        /*
        validaEntrada ve = new validaEntrada();
        
        try{
           ve.validaNomeFantasia(nomeForn.getText());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null," "+ex);
        }
        */
        
        if(nomeForn.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nome - Preenchimento obrigatório!");
        }
        
    }//GEN-LAST:event_nomeFornActionPerformed

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed
        if(cnpj.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"CNPJ - Preenchimento obrigatório!");
        }
    }//GEN-LAST:event_cnpjActionPerformed

    private void numeroFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFornActionPerformed
        if(numeroForn.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Número do Endereço - Preenchimento obrigatório!");
        }
    }//GEN-LAST:event_numeroFornActionPerformed

    private void razaoSocFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaoSocFornActionPerformed
        if(razaoSocForn.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nome - Preenchimento obrigatório!");
        }
    }//GEN-LAST:event_razaoSocFornActionPerformed

    private void inscEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscEstActionPerformed
        if(inscEst.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nome - Preenchimento obrigatório!");
        }
    }//GEN-LAST:event_inscEstActionPerformed

    private void estadoFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoFornActionPerformed

    private void cidadeFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeFornActionPerformed
        if(cidadeForn.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nome - Preenchimento obrigatório!");
        }
    }//GEN-LAST:event_cidadeFornActionPerformed

    private void cepFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepFornActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           try{   
               javax.swing.UIManager um = new javax.swing.UIManager();
               um.setLookAndFeel(um.getSystemLookAndFeelClassName());
           }catch(Exception e){
               e.printStackTrace();
           }
           finally {
                new TelaFornCadastro().setVisible(true); //troque o nemo do frame!
            }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroForn;
    private javax.swing.JButton cadastrarForn;
    private javax.swing.JFormattedTextField cepForn;
    private javax.swing.JTextField cidadeForn;
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JComboBox<String> estadoForn;
    private javax.swing.JTextField inscEst;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nomeForn;
    private javax.swing.JTextField numeroForn;
    private javax.swing.JTextField razaoSocForn;
    private javax.swing.JTextField ruaForn;
    private javax.swing.JFormattedTextField tel1Forn;
    private javax.swing.JFormattedTextField tel2Forn;
    // End of variables declaration//GEN-END:variables
}
